/**
 * Gemini AI Service
 * 
 * Generates professional government-style emergency alert messages.
 * The operator ALWAYS reviews and approves before any broadcast.
 * This service only ASSISTS the operator — it never auto-broadcasts.
 */

import type { IncidentType, IncidentPriority } from '@/types'

const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY as string
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent'

const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions'
const OPENROUTER_API_KEY = (import.meta.env.VITE_OPENROUTER_API_KEY as string) || ''

export interface IncidentContext {
  incidentType: IncidentType
  priority: IncidentPriority
  location: string
  description: string
}

export interface GeneratedAlert {
  english: string
  tagalog: string
}

const ENGLISH_PROMPT = (ctx: IncidentContext) => `
You are the official emergency communications officer for Barangay 178, Camarin, Caloocan City, Philippines.

Your task is to rewrite the following raw emergency incident description into a clear, concise, and highly actionable Emergency Alert Message for public broadcast. Do NOT summarize this like an essay.

Incident Details:
- Incident Type: ${ctx.incidentType}
- Priority Level: ${ctx.priority}
- Incident Location: ${ctx.location}
- Raw Incident Description: ${ctx.description}

Instructions for the Alert Message:
1. Identify the event type (e.g., Fire, Flood, Crime, Medical emergency).
2. State the immediate area/location clearly so residents know if they are affected.
3. Provide a clear, actionable directive for residents (e.g., evacuate, stay indoors, yield to emergency vehicles).
4. Keep it calm, authoritative, brief, and under 3 sentences.
5. Use extremely simple, clear, and direct English vocabulary. Do NOT use complex, deep, formal, or technical terms that might be difficult for a simple citizen to understand.
6. Write ONLY the final emergency broadcast message. Do not include any intros, notes, formatting prefixes, or conversational filler.

Emergency Alert Message:
`.trim()

const TAGALOG_PROMPT = (ctx: IncidentContext) => `
Ikaw ang opisyal na opisina ng komunikasyon sa emerhensiya ng Barangay 178, Camarin, Caloocan City, Pilipinas.

Ang iyong layunin ay isulat muli ang raw incident description sa isang malinaw, maikli, at madaling aksyunan na Mensahe ng Alerto sa Emerhensiya para sa pampublikong broadcast. HUWAG itong ibuod na parang isang sanaysay.

Mga Detalye ng Insidente:
- Uri ng Insidente: ${ctx.incidentType}
- Antas ng Priyoridad: ${ctx.priority}
- Lokasyon: ${ctx.location}
- Raw na Paglalarawan: ${ctx.description}

Mga Instruksyon para sa Mensahe ng Alerto:
1. Tukuyin nang malinaw ang uri ng emerhensiya.
2. Ibigay ang eksaktong lokasyon para malaman ng mga residente kung sila ay apektado.
3. Magbigay ng malinaw na hakbang o aksyon na dapat gawin ng mga mamamayan (hal. lumikas, manatili sa loob ng bahay, umiwas sa daan).
4. Panatilihin itong kalmado, opisyal, at hindi lalampas sa 3 pangungusap.
5. Gumamit ng napakasimple, karaniwan, at natural na Tagalog (Taglish kung mas angkop). HUWAG gumamit ng malalalim, matatalinhaga, o pormal na salita (tulad ng "nagsasaad", "ipinababatid", "lumisan", "paglikas"). Gamitin ang mga salitang ginagamit sa pang-araw-araw na pag-uusap para maintindihan ng lahat ng tao agad.
6. Isulat LAMANG ang mismong mensahe ng alerto. Huwag magdagdag ng panimula, paliwanag, o iba pang teksto.

Mensahe ng Alerto:
`.trim()

export function getActiveAiVersion(): 'v1' | 'v2' {
  if (typeof window !== 'undefined') {
    return (localStorage.getItem('barangay_ai_version') as 'v1' | 'v2') || 'v1'
  }
  return 'v1'
}

async function callChatGPT(prompt: string): Promise<string> {
  const response = await fetch(OPENROUTER_API_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
      'HTTP-Referer': typeof window !== 'undefined' ? window.location.origin : 'http://localhost:5173',
      'X-Title': 'Barangay 178 Emergency Portal',
    },
    body: JSON.stringify({
      model: 'openai/gpt-3.5-turbo',
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
      temperature: 0.3,
      max_tokens: 300,
    }),
  })

  if (!response.ok) {
    const error = await response.text()
    throw new Error(`ChatGPT API error: ${response.status} — ${error}`)
  }

  const data = await response.json()
  const text = data?.choices?.[0]?.message?.content

  if (!text) {
    throw new Error('No response generated by ChatGPT.')
  }

  return text.trim()
}

async function callGemini(prompt: string): Promise<string> {
  if (getActiveAiVersion() === 'v2') {
    return callChatGPT(prompt)
  }

  if (!GEMINI_API_KEY || GEMINI_API_KEY === 'your_gemini_api_key_here') {
    throw new Error('Gemini API key not configured. Please set VITE_GEMINI_API_KEY in your .env file.')
  }

  const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [
            {
              text: prompt,
            },
          ],
        },
      ],
      generationConfig: {
        temperature: 0.3,
        maxOutputTokens: 300,
        topP: 0.8,
      },
      safetySettings: [
        {
          category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
          threshold: 'BLOCK_MEDIUM_AND_ABOVE',
        },
      ],
    }),
  })

  if (!response.ok) {
    const error = await response.text()
    throw new Error(`Gemini API error: ${response.status} — ${error}`)
  }

  const data = await response.json()
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text

  if (!text) {
    throw new Error('No response generated by Gemini AI.')
  }

  return text.trim()
}

/**
 * Generate an English emergency alert message using Gemini AI.
 * The operator must review and approve before broadcasting.
 */
export async function generateEnglishAlert(ctx: IncidentContext): Promise<string> {
  return callGemini(ENGLISH_PROMPT(ctx))
}

/**
 * Generate a Tagalog emergency alert message using Gemini AI.
 * The operator must review and approve before broadcasting.
 */
export async function generateTagalogAlert(ctx: IncidentContext): Promise<string> {
  return callGemini(TAGALOG_PROMPT(ctx))
}

/**
 * Generate both English and Tagalog alerts simultaneously.
 * The operator must review and approve before broadcasting.
 */
export async function generateBothAlerts(ctx: IncidentContext): Promise<GeneratedAlert> {
  const [english, tagalog] = await Promise.all([
    generateEnglishAlert(ctx),
    generateTagalogAlert(ctx),
  ])
  return { english, tagalog }
}

export function isGeminiConfigured(): boolean {
  if (getActiveAiVersion() === 'v2') {
    return !!(OPENROUTER_API_KEY && OPENROUTER_API_KEY.startsWith('sk-or-'))
  }
  return !!(GEMINI_API_KEY && GEMINI_API_KEY !== 'your_gemini_api_key_here')
}

export interface DetectionAndTranslation {
  detected_language: 'English' | 'Tagalog'
  translated_text: string
}

/**
 * Automatically detects language (English or Tagalog) and translates to the opposite language.
 */
export async function detectAndTranslateIncident(description: string): Promise<DetectionAndTranslation> {
  if (!description || !description.trim()) {
    return { detected_language: 'English', translated_text: '' }
  }

  const prompt = `
You are a bilingual emergency communication processor. Detect if the input emergency log is in English or Tagalog. Translate it to the OPPOSITE language. Keep the tone accurate and clear for local barangay officials.

Input Emergency Log:
"${description.trim()}"

Output your response strictly in the following JSON format:
{
  "detected_language": "English or Tagalog",
  "translated_text": "Write the translated text here"
}

Do not write any markdown codeblock formatting, preamble, introductions, or conversational notes. Output only the raw JSON.
  `.trim()

  const responseText = await callGemini(prompt)
  try {
    const cleanText = responseText.replace(/```json/i, '').replace(/```/g, '').trim()
    const parsed = JSON.parse(cleanText)
    if (parsed.detected_language && parsed.translated_text) {
      return {
        detected_language: parsed.detected_language.includes('Tagalog') ? 'Tagalog' : 'English',
        translated_text: parsed.translated_text.trim(),
      }
    }
    throw new Error('Incomplete JSON response')
  } catch (err) {
    console.error('Failed to parse detect & translate JSON from Gemini:', err, responseText)
    // Fallback detection logic if JSON parse fails
    const containsTagalog = /[ng\s]mga|[sa\s]tulong|nasunog|baha|insidente|sakolo|sunog/i.test(description)
    return {
      detected_language: containsTagalog ? 'Tagalog' : 'English',
      translated_text: description,
    }
  }
}
